import type { GetStaticProps } from 'next';
import Head from 'next/head';
import About from '../components/About';
import Header from '../components/Header';
import Hero from '../components/Hero';
import WorkExperience from '../components/WorkExperience';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contacts from '../components/Contacts';
import Link from 'next/link';
import Image from 'next/image';
import {
	Contact,
	Experience,
	PageInfo,
	Project,
	Skill,
	Social,
} from '../typings';
import { fetchPageInfo } from '../utils/fetchPageInfo';
import { fetchExperience } from '../utils/fetchExperience';
import { fetchSkills } from '../utils/fetchSkills';
import { fetchSocials } from '../utils/fetchSocials';
import { fetchProjects } from '../utils/fetchProjects';
import { fetchContact } from '../utils/fetchContact';

type Props = {
	pageInfo: PageInfo;
	experience: Experience[];
	skills: Skill[];
	projects: Project[];
	socials: Social[];
	contact: Contact;
};

const Home = ({
	pageInfo,
	experience,
	skills,
	projects,
	socials,
	contact,
}: Props) => {
	return (
		<div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80'>
			<Head>
				<title>{pageInfo?.name} - Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header socials={socials} />

			{/* { Hero } */}
			<section id='hero' className='snap-start'>
				<Hero pageInfo={pageInfo} />
			</section>

			<section id='about' className='snap-center'>
				<About pageInfo={pageInfo} />
			</section>

			<section id='experience' className='snap-start'>
				<WorkExperience experience={experience} />
			</section>

			<section id='skills' className='snap-center'>
				<Skills skills={skills} />
			</section>

			<section id='projects' className='snap-start'>
				<Projects projects={projects} />
			</section>

			<section id='contact' className='snap-end'>
				<Contacts contact={contact} />
			</section>

			<Link href='#hero'>
				<footer className='sticky bottom-5 w-full cursor-pointer'>
					<div className='flex items-center justify-center'>
						<Image
							className='rounded-full filter grayscale hover:grayscale-0 cursor-pointer'
							src='https://drive.google.com/uc?export=view&id=1kmDEfj9UY3rQafKB7hpdTu8I_uDHAJ2m&rl'
							height={20}
							width={20}
							alt=''
						/>
					</div>
				</footer>
			</Link>
		</div>
	);
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
	const pageInfo: PageInfo[] = await fetchPageInfo();
	const experience: Experience[] = await fetchExperience();
	const skills: Skill[] = await fetchSkills();
	const projects: Project[] = await fetchProjects();
	const socials: Social[] = await fetchSocials();
	const contact: Contact[] = await fetchContact();

	return {
		props: {
			socials,
			pageInfo,
			experience,
			skills,
			projects,
			contact,
		},
		// Next.js will attempt to re-generate the page
		// when a request comes in
		// At most once every 10 seconds
		revalidate: 10,
	};
};

